language: ruby
cache: bundler
rvm:
  - 2.1.0
branches:
  only:
    - master # branch to build
env:
  global:
    - GH_COMMIT_AUTHOR="Travis CI"
    - GH_COMMIT_EMAIL=info@mapc.org
script:
  - bundle exec rake travis:script
after_success:
  - bundle exec rake travis:after_success
